version: '3'
services:
  web:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - 80:80
    volumes:
      - ./app/htdocs:/var/www/html
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./app/htdocs:/var/www/html
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
    volumes:
      - ./db/data:/var/lib/mysql"
      - ./db/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8888:80
    restart: always
    depends_on:
      - db